# SPDX-FileCopyrightText: The LineageOS Project
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "extract-utils"
SPDX-PackageSupplier = "The LineageOS Project"
SPDX-PackageDownloadLocation = "https://github.com/LineageOS/android_tools_extract-utils"

[[annotations]]
path = [
    ".github/workflows/**",
    ".gitignore",
    ".pre-commit-config.yaml",
    ".python-version",
    "AGENTS.md",
    "pylintrc.toml",
    "pyproject.toml",
    "ruff.toml",
    "uv.lock",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "The LineageOS Project"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "extract_utils/prebuilts/extract-tools/common/apktool/apktool.jar",
    "extract_utils/prebuilts/extract-tools/linux-x86/bin/stripzip",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "The LineageOS Project"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "extract_utils/prebuilts/extract-tools/linux-x86/bin/patchelf-0_17_2",
    "extract_utils/prebuilts/extract-tools/linux-x86/bin/patchelf-0_18",
    "extract_utils/prebuilts/extract-tools/linux-x86/bin/patchelf-0_8",
    "extract_utils/prebuilts/extract-tools/linux-x86/bin/patchelf-0_9",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Eelco Dolstra"
SPDX-License-Identifier = "GPL-3.0-or-later"
